apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "${K8S_NAME}"
  namespace: "${K8S_NAMESPACE}"
  labels:
    app: "${K8S_APP}"
    component: "${K8S_NAME}"
    tier: "${K8S_TIER}"
    environment: "${APP_ENV}"
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "${K8S_APP}"
      component: "${K8S_NAME}"
      tier: "${K8S_TIER}"
      environment: "${APP_ENV}"
  template:
    metadata:
      labels:
        app: "${K8S_APP}"
        component: "${K8S_NAME}"
        tier: "${K8S_TIER}"
        environment: "${APP_ENV}"
    spec:
      containers:
      - name: "${K8S_NAME}"
        image: "${DOCKER_IMAGE}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: ${K8S_PORT}
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: ${K8S_PORT}
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: ${K8S_PORT}
          initialDelaySeconds: 30
          timeoutSeconds: 30
      imagePullSecrets:
      - name: "${DOCKER_REGISTRY}"

